### ISSUE TITLE
"Geobookmark" or "Geofavorite"

### ISSUE THREAD

**Issue by Valdnet** [penguin86/nextcloud-maps-client#10]
Inconsistency in text strings.
For example, in the header and in the information of the delete window, geobookmark is:

https://github.com/penguin86/nextcloud-maps-client/blob/e64b89bce61b66416ac1c5d5efe1ff7dfcf000f4/app/src/main/res/values/strings.xml#L36
https://github.com/penguin86/nextcloud-maps-client/blob/e64b89bce61b66416ac1c5d5efe1ff7dfcf000f4/app/src/main/res/values/strings.xml#L37

However, the delete message already contains "geofavorite":

https://github.com/penguin86/nextcloud-maps-client/blob/e64b89bce61b66416ac1c5d5efe1ff7dfcf000f4/app/src/main/res/values/strings.xml#L40-L41

In my opinion it should be "geobookmark" if we refer to "geofavorites". Same here, it should be standardized whether it is about "geobookmark" or "geofavorites".

https://github.com/penguin86/nextcloud-maps-client/blob/e64b89bce61b66416ac1c5d5efe1ff7dfcf000f4/app/src/main/res/values/strings.xml#L58
https://github.com/penguin86/nextcloud-maps-client/blob/e64b89bce61b66416ac1c5d5efe1ff7dfcf000f4/app/src/main/res/values/strings.xml#L60

**Comment by penguin86** [comment]
Fixed in v0.3.4
