### ISSUE TITLE
How can I show my Geofavorites in Nextcloud Map?

### ISSUE THREAD

**Issue by blogdemoi** [penguin86/nextcloud-maps-client#19]
Hello,

How can I have my Geofavorites created with the "Nextcloud Maps Geobookmarks" appeared on the Nextcloud map?

Thank you.

**Comment by penguin86** [comment]
Hello, if the app is logged with the same account of the web, they should just work.
Can you please check in Nextcloud Maps web if the "My favorites" menu on the left is greyed out? It shouldn't, if it is, please click it to activate the geobookmarks overlay. Plus, once clicked you should see the list of categories in the dropdown.

You can as well try to create a geofavorite on the web and see if it pops up on the app.

**Comment by blogdemoi** [comment]
Thank you, it worked. I tried to create a favorite from my phone then from Nextcloud Maps web and both favorites appear on the Nextcloud Maps web and in the Android application. Don't know what happened when I tried the other day, sorry for the false alert :-)

**Comment by penguin86** [comment]
Nice to hear it is working for you!
I'll close this issue.
Have a good day!
