### ISSUE TITLE
Feature Request: Show existing Favorites on Add New map preview

### ISSUE THREAD

**Issue by Saijin-Naib** [penguin86/nextcloud-maps-client#24]
Any existing Favorites should be shown on the preview map if in view.

**Comment by penguin86** [comment]
Hello Saijin-Naib,
I just released v0.4.0, and now a navigable map view is present.
![Navigable map](https://raw.githubusercontent.com/penguin86/nextcloud-maps-client/master/screenshots/2.png)
This should solve your use case. Having this navigable map, I think it no more makes sense to show existing favourites in the small, non-navigable map in geofavorite detail view.
