### ISSUE TITLE
Category icon

### ISSUE THREAD

**Issue by Valdnet** [penguin86/nextcloud-maps-client#6]
The category icon is associated more with the lack of a user avatar rather than a category. You should change the icon to, for example, "Location", which will be more associated with the categories of locations.

![obraz](https://user-images.githubusercontent.com/47037905/138560111-01aa7250-6b9e-4d43-b075-9abce818bc88.png)

App:
Nextcloud Maps Geobookmarks v0.3.3

**Comment by penguin86** [comment]
Available in v0.3.4
