### ISSUE TITLE
Text edit cursor

### ISSUE THREAD

**Issue by Valdnet** [penguin86/nextcloud-maps-client#8]
The text edit cursor should not be black in color. I propose to match the color to the theme of the application.

![obraz](https://user-images.githubusercontent.com/47037905/138560383-437985c3-3941-43fe-9dd9-a8feb2aaa532.png)

App:
Nextcloud Maps Geobookmarks v0.3.3

**Comment by penguin86** [comment]
Done in v0.3.4
